env: "local"
storage_path: "storage/storage.db"  # using sqlite database for now
http_server: 
  host: "localhost"
  port: 8075
  timeout: 4s        # request timeout
  idle_timeout: 60s  # idle connection timeout